apiVersion: v1
kind: Pod
metadata:
  labels:
    app: k6
  name: k6-sample-initializer-qxrnk
  namespace: default
spec:
  automountServiceAccountToken: true
  containers:
  - command:
    - sh
    - -c
    - sleep 10000
    image: ghcr.io/grafana/k6-operator:latest-runner
    imagePullPolicy: IfNotPresent
    name: k6
    volumeMounts:
    - mountPath: /test
      name: k6-test-volume
  volumes:
  - name: k6-test-volume
    persistentVolumeClaim:
      claimName: perf-test
