# 

apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: crypter-load
spec:
  parallelism: 2 
  script:
    volumeClaim:
      name: perf-test
      file: api-test.js
  separate: false
  runner:
    env:
      - name: CRYPTER_API_URL
        value: 'http://crypter:8080'
