# k6-resource.yml

apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-sample
spec:
  parallelism: 4
  script:
    volumeClaim:
      name: perf-test
      file: api-test.js
  separate: false
