name: Docker Image CI

on:
  push:
    branches: [ "main", "fixalloc" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PAT }}
    - name: Set branch
      run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: otomato/crypter:${{ env.GITHUB_REF_NAME }}
        platforms: linux/amd64,linux/arm64
        build-args: |
          BRANCH=${{ env.BRANCH }}
